#!/usr/bin/env python3

# nofapy: A free NOFAP counter program written in Python.
# Copyright (C) 2024 SurnameGuy (https://github.com/SurnameGuy)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.



# Recado para desenvolvedores: Eu sei, meu código está feio e está cheio de coisas desnecessárias. Fiz este programa rapidamente e apenas para fins de entretenimento. Peço para que desconsidere. Caso queira contribuir com o projeto, fique à vontade.

# >===> Importar módulos
import os, sys, webbrowser, time
from datetime import datetime, timedelta
from pathlib import Path
# Checa se o programa está sendo executado como super-usuário. Se sim, termina o programa e retorna um erro.
if 'SUDO_UID' in os.environ:
    print("ERRO: Este programa não pode ser executado com privilégios de super-usuário, ou desastres podem acontecer!")
    exit(1)

##########    [ VARIÁVEIS ]    ##########
# Define as variáveis como globais.
global homepath, sospage, nofapvar, nopornvar, timenow, shouldquit
homepath = str(Path.home())
# Define as variáveis iniciais.
shouldquit = ""
nofapvar = f'{homepath}/.config/nofapy/nofap.var'
nopornvar = f'{homepath}/.config/nofapy/noporn.var'
reasonvar = f'{homepath}/.config/nofapy/reason.var'
sospage = f'{homepath}/.config/nofapy/sospage.html'
timenow = datetime.now()

##########     [ FUNÇÕES ]     ##########
# Deleta um arquivo. Caso ele não exista, retorna None.
def deletefile(filepath):
    try:
        return os.remove(filepath)
    except:
        return None
# Função para criar um novo arquivo. Caso o caminho não exista, ele irá criar.
def makefile(filepath):
    directory = os.path.dirname(filepath)
    if not os.path.exists(directory):
        os.makedirs(directory)
    return open(filepath, 'w').close()
# Função para escrever em um arquivo.
def writefile(filepath, content):
    open(filepath, 'w').write(str(content))
# Função para ler um arquivo. Caso não exista, retorna None.
def readfile(filepath):
    try:
        return open(filepath, 'r').read()
    except:
        return None
# Função para comparar duas datas
def comparetime(oldtime, newtime):
    difference = (newtime - oldtime)
    # timed = seconds=
    time = timedelta(seconds=difference.total_seconds())
    time = str(time).replace(" ", "").replace("days", "").replace("day", "").replace(":", ",").split(".")[0].split(",")
    if len(time) == 3:
        return f"0 dia ({time[0]}h:{time[1]}m:{time[2]}s)"
    if len(time) == 4:
        if int(time[0]) > 1:
            s = "s"
        else:
            s = ""
        return f"{time[0]} dia{s} ({time[1]}h:{time[2]}m:{time[3]}s)"

# Define o Nofapy para os padrões de fábrica caso o argumento "--reset-all" seja utilizado.
try:
    if (sys.argv[1] == "--reset-all"):
        confirm = input("Tem certeza que deseja redefinir o Nofapy para os padrões de fábrica? (s/N): ")
        if confirm.lower() == "s":
            deletefile(nofapvar)
            deletefile(nopornvar)
            deletefile(reasonvar)
            deletefile(sospage)
            print("Nofapy redefinido para os padrões de fábrica.")
            shouldquit = True
        else:
            print("Cancelado.")
            shouldquit = True
except:
    None
if shouldquit == True:
    exit()

if readfile(nofapvar) == None:
    makefile(nofapvar)
    writefile(nofapvar, timenow)
    print()

if readfile(nopornvar) == None:
    makefile(nopornvar)
    writefile(nopornvar, timenow)

if readfile(reasonvar) == None:
    makefile(reasonvar)
    writefile(reasonvar, "")

if readfile(sospage) == None:
    print("Olá! Seja bem-vindo ao Nofapy. Parece que essa é a sua primeira vez executando o programa. Digite --help para obter uma lista de ajuda.")
    makefile(sospage)
    writefile(sospage, "<html style='display:flex;flex-direction:row;justify-content:center;align-items:center;height:100vh;text-align:center;></html><head><meta charset='UTF-8'><title>NÃO FAÇA ISSO!</title></head><div'><meta charset='utf8'><h1 style='color:red'>⚠ ATENÇÃO! ⚠</h1><br><h2>Continue firme, guerreiro. Não recaia, não venda a sua alma para Satanás!<br><br>Eu abri 3 guias no seu navegador com o conteúdo necessário para que você não recaia.<br><br>Mantenha-se firme e forte, reze a oração de São Bento, uma dezena do Santo Rosário e não se deixe tentar.</h2><br><br><br><br><br><h3 style='color:orange'>✝ Crux Sacra Sit Mihi Lux. Non Draco Sit Mihi Dux. Vade Retro Satana! Nunquam Suade Mihi Vana. Sunt Mala Quae Libas. Ipse Venena Bibas. ✝</h3></div></html>")

nofapdate = datetime.strptime(readfile(nofapvar), "%Y-%m-%d %H:%M:%S.%f")
noporndate = datetime.strptime(readfile(nopornvar), "%Y-%m-%d %H:%M:%S.%f")

nofaptime = comparetime(nofapdate, timenow)
noporntime = comparetime(noporndate, timenow)
# print(nofapdate)
# print(noporndate)
# print(datetime.now())

def timer():
    print(f"Tempo de NOFAP: {nofaptime}")
    print(f"Tempo de NOPORN: {noporntime}")
    print()
    if len(readfile(reasonvar)) == 0:
        print(f'Motivo da última recaída: ———')
    else:
        print(f'Motivo da última recaída: {readfile(reasonvar)}')

def reason():
    reason = input("Digito o motivo da recaída, ou deixe em branco para pular: ")
    if len(reason) > 0:
        deletefile(reasonvar)
        writefile(reasonvar, reason)
    else:
        deletefile(reasonvar)

# Commands
try:
    if (sys.argv[1] == "--help") or (sys.argv[1] == "-h"):
        print(f"Nofapy | v2.0 | Licensa: GNU GPL 3")
        print(f">==========> AJUDA <==========<")
        print(f"Digite --help ou -h para acessar o comando de ajuda.")
        print(f"Digite --recaida-nofap para resetar a contagem do NOFAP.")
        print(f"Digite --recaida-noporn para resetar a contagem do NOPORN.")
        print(f"Digite --recaida-geral para resetar a contagem do NOFAP e do NOPORN.")
        print(f"Digite --emergencia, --socorro, --sos ou -s em caso de emergência e risco de recaída (Apenas em Inglês).")
        print(f"(Para uso em scripts e integrações, utilize -ss para o comando de emergência)")
        print(f"Digite --reset-all para reiniciar o programa com os padrões de fábrica.")

    elif (sys.argv[1] == "--emergencia") or (sys.argv[1] == "--socorro") or (sys.argv[1] == "--sos") or (sys.argv[1] == "-s"):
        print("Abrindo guias de emergência no seu navegador padrão...")
        webbrowser.open("https://emergency.nofap.com/redirect?religious=true&queryString=em&cat=em&cat=rej&cat=dep&cat=rel")
        webbrowser.open("https://emergency.nofap.com/redirect?religious=true&queryString=em&cat=em&cat=rej&cat=dep&cat=rel")
        webbrowser.open("https://emergency.nofap.com/redirect?religious=true&queryString=em&cat=em&cat=rej&cat=dep&cat=rel")
        webbrowser.open(f"file://{sospage}")

    elif (sys.argv[1] == "-ss"):
        webbrowser.open("https://emergency.nofap.com/redirect?religious=true&queryString=em&cat=em&cat=rej&cat=dep&cat=rel")

    elif sys.argv[1] == "--recaida-nofap":
        confirm = input("Tem certeza que deseja resetar a sua contagem do NOFAP? (s/N): ")
        if confirm.lower() == "s":
            reason()
            deletefile(nofapvar)
            print("A sua contagem do NOFAP foi resetada. Execute o Nofapy quando estiver pronto para re-começar a sua contagem do NOFAP.")
        else:
            print("Cancelado.")

    elif sys.argv[1] == "--recaida-noporn":
        confirm = input("Tem certeza que deseja resetar a sua contagem do NOPORN? (s/N): ")
        if confirm.lower() == "s":
            reason()
            deletefile(nopornvar)
            print("A sua contagem do NOPORN foi resetada. Execute o Nofapy quando estiver pronto para re-começar a sua contagem do NOPORN.")
        else:
            print("Cancelado.")

    elif sys.argv[1] == "--recaida-geral":
        confirm = input("Tem certeza que deseja resetar a sua contagem do NOFAP e do NOPORN? (s/N): ")
        if confirm.lower() == "s":
            reason()
            deletefile(nofapvar)
            deletefile(nopornvar)
            print("A sua contagem do NOFAP e NOPORN foi resetada. Execute o Nofapy quando estiver pronto para re-começar a sua contagem do NOFAP e do NOPORN.")
        else:
            print("Cancelado.")

    elif sys.argv[1] == "--reset-all":
        None
    else:
        print("Inválido")
except:
    timer()
